server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: user-management-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.test.web.client: INFO
    org.apache.http: INFO
    org.apache.http.wire: INFO